site_name: Stakater Handbook
docs_dir: content
site_url: https://employee.stakater.com
repo_url: https://github.com/stakater/employee-handbook
edit_uri: blob/master/content/

nav:
    - index.md
    - handbook_sweden.md
    - joining.md
    - moonlighting.md
    - nda.md
    - career-path.md
    - career-path-process.md
