name: Pull Request

on:
  pull_request:
    branches:
      - 'master'

jobs:
  qa:
    uses: stakater/.github/.github/workflows/pull_request_doc_qa.yaml@v0.0.35
    with:
      MD_CONFIG: .github/md_config.json
      DOC_SRC: content
      MD_LINT_CONFIG: markdownlint.yaml
  build:
    uses: stakater/.github/.github/workflows/pull_request_container_build.yaml@v0.0.35
    with:
      DOCKER_FILE_PATH: Dockerfile
    secrets:
      CONTAINER_REGISTRY_URL: ${{ secrets.STAKATER_NEXUS_PREPROD_REGISTRY }}
      CONTAINER_REGISTRY_USERNAME: ${{ secrets.STAKATER_NEXUS_PREPROD_USERNAME }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.STAKATER_NEXUS_PREPROD_PASSWORD }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }}
