name: Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: .github/md_config.json
  spell_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Spell check
        uses: errata-ai/vale-action@v2.0.1
        with:
          styles: https://github.com/errata-ai/write-good/releases/latest/download/write-good.zip
          files: content
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  style_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Style check
        uses: reviewdog/action-languagetool@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          reporter: github-pr-review
          level: warning
          language: 'en-US'
          patterns: '**/*.md'
