name: Push

on:
  push:
    branches:
      - 'master'

jobs:
  push:
    uses: stakater/.github/.github/workflows/push_container.yaml@v0.0.115
    with:
      DOCKER_FILE_PATH: Dockerfile
      RELEASE_BRANCH: master
    secrets:
      CONTAINER_REGISTRY_URL: ghcr.io/stakater
      CONTAINER_REGISTRY_USERNAME: ${{ github.actor }}
      CONTAINER_REGISTRY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAKATER_DELIVERY_SLACK_WEBHOOK }} 
      GH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
